//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Eng_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Eng_US", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPMENT CONTRACT.
        /// </summary>
        internal static string DevelopmentContract {
            get {
                return ResourceManager.GetString("DevelopmentContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Goals.
        /// </summary>
        internal static string FinalGoals {
            get {
                return ResourceManager.GetString("FinalGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for participant.
        /// </summary>
        internal static string ForParticipant {
            get {
                return ResourceManager.GetString("ForParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longterm Goals.
        /// </summary>
        internal static string LongtermGoals {
            get {
                return ResourceManager.GetString("LongtermGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Goals.
        /// </summary>
        internal static string MidGoals {
            get {
                return ResourceManager.GetString("MidGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Goals.
        /// </summary>
        internal static string ShortGoals {
            get {
                return ResourceManager.GetString("ShortGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong KPI`s.
        /// </summary>
        internal static string StrongKPI {
            get {
                return ResourceManager.GetString("StrongKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training milestone.
        /// </summary>
        internal static string TrainingMilestone {
            get {
                return ResourceManager.GetString("TrainingMilestone", resourceCulture);
            }
        }
    }
}
