//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.ReportAssembly.cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPS.ReportAssembly.cultures.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CONTRACT_ACTION {
            get {
                return ResourceManager.GetString("CONTRACT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Goals.
        /// </summary>
        public static string CONTRACT_BETWEEN_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_BETWEEN_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach.
        /// </summary>
        public static string CONTRACT_COACH {
            get {
                return ResourceManager.GetString("CONTRACT_COACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string CONTRACT_DEADLINE {
            get {
                return ResourceManager.GetString("CONTRACT_DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Contract.
        /// </summary>
        public static string CONTRACT_DEVELOPMENT_CONTRACT {
            get {
                return ResourceManager.GetString("CONTRACT_DEVELOPMENT_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOPMENT CONTRACT.
        /// </summary>
        public static string CONTRACT_DEVELOPMENT_CONTRACT_TITLE {
            get {
                return ResourceManager.GetString("CONTRACT_DEVELOPMENT_CONTRACT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager / Participant.
        /// </summary>
        public static string CONTRACT_DIRECTOR_CONTESTANT {
            get {
                return ResourceManager.GetString("CONTRACT_DIRECTOR_CONTESTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We agree that the above areas are discussed in a personal development interview and we commit ourselves to work purposefully, disciplined and structured to enhance performance for the benefit of employees, customers, and the company..
        /// </summary>
        public static string CONTRACT_ENHANCE_PERFORMANCE_FOR_THE_BENEFIT_OF_EMPLOYEES_CUSTOMERS_AND_THE_COMPANY {
            get {
                return ResourceManager.GetString("CONTRACT_ENHANCE_PERFORMANCE_FOR_THE_BENEFIT_OF_EMPLOYEES_CUSTOMERS_AND_THE_COMPA" +
                        "NY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation closed.
        /// </summary>
        public static string CONTRACT_EVALUATION_CLOSED {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation open.
        /// </summary>
        public static string CONTRACT_EVALUATION_OPEN {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation time.
        /// </summary>
        public static string CONTRACT_EVALUATION_TIME {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluator.
        /// </summary>
        public static string CONTRACT_EVALUATOR {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise exercises towards the next goal.
        /// </summary>
        public static string CONTRACT_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Goals.
        /// </summary>
        public static string CONTRACT_FINAL_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_FINAL_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Areas.
        /// </summary>
        public static string CONTRACT_FOCUS_AREAS {
            get {
                return ResourceManager.GetString("CONTRACT_FOCUS_AREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string CONTRACT_FOR {
            get {
                return ResourceManager.GetString("CONTRACT_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For participants.
        /// </summary>
        public static string CONTRACT_FOR_PARTICIPANTS {
            get {
                return ResourceManager.GetString("CONTRACT_FOR_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string CONTRACT_FROM {
            get {
                return ResourceManager.GetString("CONTRACT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Manager.
        /// </summary>
        public static string CONTRACT_GENERAL_MANAGER {
            get {
                return ResourceManager.GetString("CONTRACT_GENERAL_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How.
        /// </summary>
        public static string CONTRACT_HOW {
            get {
                return ResourceManager.GetString("CONTRACT_HOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long.
        /// </summary>
        public static string CONTRACT_HOW_LONG {
            get {
                return ResourceManager.GetString("CONTRACT_HOW_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many.
        /// </summary>
        public static string CONTRACT_HOW_MANY {
            get {
                return ResourceManager.GetString("CONTRACT_HOW_MANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, improve your result to pass the test..
        /// </summary>
        public static string CONTRACT_IMPROVE_YOUR_RESULT_TO_PASS {
            get {
                return ResourceManager.GetString("CONTRACT_IMPROVE_YOUR_RESULT_TO_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is Bronze!.
        /// </summary>
        public static string CONTRACT_IT_IS_BRONZE {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_BRONZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It Is Gold!.
        /// </summary>
        public static string CONTRACT_IT_IS_GOLD {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_GOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is Silver!.
        /// </summary>
        public static string CONTRACT_IT_IS_SILVER {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_SILVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders evaluation.
        /// </summary>
        public static string CONTRACT_LEADERS_EVALUATION {
            get {
                return ResourceManager.GetString("CONTRACT_LEADERS_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long term goal.
        /// </summary>
        public static string CONTRACT_LONG_TERM_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_LONG_TERM_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring interval.
        /// </summary>
        public static string CONTRACT_MEASURING_INTERVAL {
            get {
                return ResourceManager.GetString("CONTRACT_MEASURING_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string CONTRACT_MILESTONE {
            get {
                return ResourceManager.GetString("CONTRACT_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string CONTRACT_MILESTONE1 {
            get {
                return ResourceManager.GetString("CONTRACT_MILESTONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CONTRACT_NAME {
            get {
                return ResourceManager.GetString("CONTRACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of profile.
        /// </summary>
        public static string CONTRACT_NAME_OF_PROFILE {
            get {
                return ResourceManager.GetString("CONTRACT_NAME_OF_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Stage.
        /// </summary>
        public static string CONTRACT_NEXT_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_NEXT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Previous Milestone.
        /// </summary>
        public static string CONTRACT_NO_PREVIOUS_MILESTONE {
            get {
                return ResourceManager.GetString("CONTRACT_NO_PREVIOUS_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of.
        /// </summary>
        public static string CONTRACT_OUT_OF {
            get {
                return ResourceManager.GetString("CONTRACT_OUT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string CONTRACT_OVER {
            get {
                return ResourceManager.GetString("CONTRACT_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string CONTRACT_PAGE {
            get {
                return ResourceManager.GetString("CONTRACT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        public static string CONTRACT_PAGES {
            get {
                return ResourceManager.GetString("CONTRACT_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string CONTRACT_PARTICIPANT {
            get {
                return ResourceManager.GetString("CONTRACT_PARTICIPANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant leader.
        /// </summary>
        public static string CONTRACT_PARTICIPANT_LEADER {
            get {
                return ResourceManager.GetString("CONTRACT_PARTICIPANT_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string CONTRACT_POINT {
            get {
                return ResourceManager.GetString("CONTRACT_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string CONTRACT_PROFILE {
            get {
                return ResourceManager.GetString("CONTRACT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile stage.
        /// </summary>
        public static string CONTRACT_PROFILE_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_PROFILE_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string CONTRACT_PROJECT {
            get {
                return ResourceManager.GetString("CONTRACT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string CONTRACT_QUESTIONS {
            get {
                return ResourceManager.GetString("CONTRACT_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEATING TRAINING PLAN.
        /// </summary>
        public static string CONTRACT_REPEATING_TRAINING_PLAN {
            get {
                return ResourceManager.GetString("CONTRACT_REPEATING_TRAINING_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        public static string CONTRACT_REPETITION {
            get {
                return ResourceManager.GetString("CONTRACT_REPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string CONTRACT_SEE_MORE {
            get {
                return ResourceManager.GetString("CONTRACT_SEE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Goals.
        /// </summary>
        public static string CONTRACT_SHORT_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_SHORT_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string CONTRACT_SIGNATURE {
            get {
                return ResourceManager.GetString("CONTRACT_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string CONTRACT_SKILL {
            get {
                return ResourceManager.GetString("CONTRACT_SKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string CONTRACT_SKILL1 {
            get {
                return ResourceManager.GetString("CONTRACT_SKILL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string CONTRACT_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CONTRACT_START {
            get {
                return ResourceManager.GetString("CONTRACT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string CONTRACT_START_DATE {
            get {
                return ResourceManager.GetString("CONTRACT_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Score.
        /// </summary>
        public static string CONTRACT_START_SCORE {
            get {
                return ResourceManager.GetString("CONTRACT_START_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Stage.
        /// </summary>
        public static string CONTRACT_START_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_START_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong KPIs.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong KPIs: Exercise exercises towards the next goal.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong KPIs Goals.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong KPIs: Repetitive training details.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_REPETITIVE_TRAINING_DETAILS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_REPETITIVE_TRAINING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Date/Time.
        /// </summary>
        public static string CONTRACT_SURVEY_DATE_TIME {
            get {
                return ResourceManager.GetString("CONTRACT_SURVEY_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Results.
        /// </summary>
        public static string CONTRACT_SURVEY_RESULTS {
            get {
                return ResourceManager.GetString("CONTRACT_SURVEY_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string CONTRACT_TARGET {
            get {
                return ResourceManager.GetString("CONTRACT_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string CONTRACT_TO {
            get {
                return ResourceManager.GetString("CONTRACT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string CONTRACT_TRAINING {
            get {
                return ResourceManager.GetString("CONTRACT_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Exercises.
        /// </summary>
        public static string CONTRACT_TRAINING_EXERCISES {
            get {
                return ResourceManager.GetString("CONTRACT_TRAINING_EXERCISES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak KPIs.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak KPIs: Exercise exercises towards the next goal.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak KPIs Goals.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak KPIs: Repetitive training details.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_REPETITIVE_TRAINING_DETAILS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_REPETITIVE_TRAINING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        public static string CONTRACT_WHAT {
            get {
                return ResourceManager.GetString("CONTRACT_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why.
        /// </summary>
        public static string CONTRACT_WHY {
            get {
                return ResourceManager.GetString("CONTRACT_WHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You answered.
        /// </summary>
        public static string CONTRACT_YOU_ANSWERED {
            get {
                return ResourceManager.GetString("CONTRACT_YOU_ANSWERED", resourceCulture);
            }
        }
    }
}
