//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.ReportAssembly.cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class nb_NO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nb_NO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPS.ReportAssembly.cultures.nb-NO", typeof(nb_NO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling.
        /// </summary>
        public static string CONTRACT_ACTION {
            get {
                return ResourceManager.GetString("CONTRACT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mellom Mål.
        /// </summary>
        public static string CONTRACT_BETWEEN_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_BETWEEN_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trener.
        /// </summary>
        public static string CONTRACT_COACH {
            get {
                return ResourceManager.GetString("CONTRACT_COACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidsfrist.
        /// </summary>
        public static string CONTRACT_DEADLINE {
            get {
                return ResourceManager.GetString("CONTRACT_DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utviklingskontrakt.
        /// </summary>
        public static string CONTRACT_DEVELOPMENT_CONTRACT {
            get {
                return ResourceManager.GetString("CONTRACT_DEVELOPMENT_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTVIKLINGSKONTRAKT.
        /// </summary>
        public static string CONTRACT_DEVELOPMENT_CONTRACT_TITLE {
            get {
                return ResourceManager.GetString("CONTRACT_DEVELOPMENT_CONTRACT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leder/Deltager.
        /// </summary>
        public static string CONTRACT_DIRECTOR_CONTESTANT {
            get {
                return ResourceManager.GetString("CONTRACT_DIRECTOR_CONTESTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi er enige om at ovennevnte områder er diskutert i en personlig utviklingssamtale og vi forplikter oss gjensidig i å arbeide målbevisst, disiplinert og strukturert for å øke prestasjoner til beste for medarbeider, kunder og selskapet..
        /// </summary>
        public static string CONTRACT_ENHANCE_PERFORMANCE_FOR_THE_BENEFIT_OF_EMPLOYEES_CUSTOMERS_AND_THE_COMPANY {
            get {
                return ResourceManager.GetString("CONTRACT_ENHANCE_PERFORMANCE_FOR_THE_BENEFIT_OF_EMPLOYEES_CUSTOMERS_AND_THE_COMPA" +
                        "NY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluering stengt.
        /// </summary>
        public static string CONTRACT_EVALUATION_CLOSED {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluering åpen.
        /// </summary>
        public static string CONTRACT_EVALUATION_OPEN {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluerings tidspunkt.
        /// </summary>
        public static string CONTRACT_EVALUATION_TIME {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluator.
        /// </summary>
        public static string CONTRACT_EVALUATOR {
            get {
                return ResourceManager.GetString("CONTRACT_EVALUATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treningsøvelser frem mot neste mål.
        /// </summary>
        public static string CONTRACT_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endelige Mål.
        /// </summary>
        public static string CONTRACT_FINAL_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_FINAL_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fokusområder.
        /// </summary>
        public static string CONTRACT_FOCUS_AREAS {
            get {
                return ResourceManager.GetString("CONTRACT_FOCUS_AREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til.
        /// </summary>
        public static string CONTRACT_FOR {
            get {
                return ResourceManager.GetString("CONTRACT_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For deltager.
        /// </summary>
        public static string CONTRACT_FOR_PARTICIPANTS {
            get {
                return ResourceManager.GetString("CONTRACT_FOR_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fra.
        /// </summary>
        public static string CONTRACT_FROM {
            get {
                return ResourceManager.GetString("CONTRACT_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overordnet Leder.
        /// </summary>
        public static string CONTRACT_GENERAL_MANAGER {
            get {
                return ResourceManager.GetString("CONTRACT_GENERAL_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvordan.
        /// </summary>
        public static string CONTRACT_HOW {
            get {
                return ResourceManager.GetString("CONTRACT_HOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvor lenge.
        /// </summary>
        public static string CONTRACT_HOW_LONG {
            get {
                return ResourceManager.GetString("CONTRACT_HOW_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvor mange.
        /// </summary>
        public static string CONTRACT_HOW_MANY {
            get {
                return ResourceManager.GetString("CONTRACT_HOW_MANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vær så snill, forbedrer resultatet for å bestå testen..
        /// </summary>
        public static string CONTRACT_IMPROVE_YOUR_RESULT_TO_PASS {
            get {
                return ResourceManager.GetString("CONTRACT_IMPROVE_YOUR_RESULT_TO_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er bronse!.
        /// </summary>
        public static string CONTRACT_IT_IS_BRONZE {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_BRONZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er gull!.
        /// </summary>
        public static string CONTRACT_IT_IS_GOLD {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_GOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er sølv!.
        /// </summary>
        public static string CONTRACT_IT_IS_SILVER {
            get {
                return ResourceManager.GetString("CONTRACT_IT_IS_SILVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leders evaluering.
        /// </summary>
        public static string CONTRACT_LEADERS_EVALUATION {
            get {
                return ResourceManager.GetString("CONTRACT_LEADERS_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langsiktige Mål.
        /// </summary>
        public static string CONTRACT_LONG_TERM_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_LONG_TERM_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målingsintervall.
        /// </summary>
        public static string CONTRACT_MEASURING_INTERVAL {
            get {
                return ResourceManager.GetString("CONTRACT_MEASURING_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string CONTRACT_MILESTONE {
            get {
                return ResourceManager.GetString("CONTRACT_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milepæl.
        /// </summary>
        public static string CONTRACT_MILESTONE1 {
            get {
                return ResourceManager.GetString("CONTRACT_MILESTONE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string CONTRACT_NAME {
            get {
                return ResourceManager.GetString("CONTRACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på profil.
        /// </summary>
        public static string CONTRACT_NAME_OF_PROFILE {
            get {
                return ResourceManager.GetString("CONTRACT_NAME_OF_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neste nivå.
        /// </summary>
        public static string CONTRACT_NEXT_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_NEXT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen tidligere milepæl.
        /// </summary>
        public static string CONTRACT_NO_PREVIOUS_MILESTONE {
            get {
                return ResourceManager.GetString("CONTRACT_NO_PREVIOUS_MILESTONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ut av.
        /// </summary>
        public static string CONTRACT_OUT_OF {
            get {
                return ResourceManager.GetString("CONTRACT_OUT_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string CONTRACT_OVER {
            get {
                return ResourceManager.GetString("CONTRACT_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string CONTRACT_PAGE {
            get {
                return ResourceManager.GetString("CONTRACT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sider.
        /// </summary>
        public static string CONTRACT_PAGES {
            get {
                return ResourceManager.GetString("CONTRACT_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltaker.
        /// </summary>
        public static string CONTRACT_PARTICIPANT {
            get {
                return ResourceManager.GetString("CONTRACT_PARTICIPANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltakers leder.
        /// </summary>
        public static string CONTRACT_PARTICIPANT_LEADER {
            get {
                return ResourceManager.GetString("CONTRACT_PARTICIPANT_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poeng.
        /// </summary>
        public static string CONTRACT_POINT {
            get {
                return ResourceManager.GetString("CONTRACT_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string CONTRACT_PROFILE {
            get {
                return ResourceManager.GetString("CONTRACT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil stadie.
        /// </summary>
        public static string CONTRACT_PROFILE_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_PROFILE_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekt.
        /// </summary>
        public static string CONTRACT_PROJECT {
            get {
                return ResourceManager.GetString("CONTRACT_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørsmål.
        /// </summary>
        public static string CONTRACT_QUESTIONS {
            get {
                return ResourceManager.GetString("CONTRACT_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPETERENDE TRENINGS PLAN.
        /// </summary>
        public static string CONTRACT_REPEATING_TRAINING_PLAN {
            get {
                return ResourceManager.GetString("CONTRACT_REPEATING_TRAINING_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetering.
        /// </summary>
        public static string CONTRACT_REPETITION {
            get {
                return ResourceManager.GetString("CONTRACT_REPETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se mer.
        /// </summary>
        public static string CONTRACT_SEE_MORE {
            get {
                return ResourceManager.GetString("CONTRACT_SEE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte Mål.
        /// </summary>
        public static string CONTRACT_SHORT_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_SHORT_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatur.
        /// </summary>
        public static string CONTRACT_SIGNATURE {
            get {
                return ResourceManager.GetString("CONTRACT_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string CONTRACT_SKILL {
            get {
                return ResourceManager.GetString("CONTRACT_SKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdighet.
        /// </summary>
        public static string CONTRACT_SKILL1 {
            get {
                return ResourceManager.GetString("CONTRACT_SKILL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milepel.
        /// </summary>
        public static string CONTRACT_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CONTRACT_START {
            get {
                return ResourceManager.GetString("CONTRACT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start dato.
        /// </summary>
        public static string CONTRACT_START_DATE {
            get {
                return ResourceManager.GetString("CONTRACT_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Score.
        /// </summary>
        public static string CONTRACT_START_SCORE {
            get {
                return ResourceManager.GetString("CONTRACT_START_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scenen.
        /// </summary>
        public static string CONTRACT_START_STAGE {
            get {
                return ResourceManager.GetString("CONTRACT_START_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterke KPI`er.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterke KPIer : Treningsøvelser frem mot neste mål.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterke KPIer Mål.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterke KPIer : Repeterende treningsdetaljer.
        /// </summary>
        public static string CONTRACT_STRONG_KPIS_REPETITIVE_TRAINING_DETAILS {
            get {
                return ResourceManager.GetString("CONTRACT_STRONG_KPIS_REPETITIVE_TRAINING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil undersøkelse/Dato/Tid.
        /// </summary>
        public static string CONTRACT_SURVEY_DATE_TIME {
            get {
                return ResourceManager.GetString("CONTRACT_SURVEY_DATE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultater Profil undersøkelse.
        /// </summary>
        public static string CONTRACT_SURVEY_RESULTS {
            get {
                return ResourceManager.GetString("CONTRACT_SURVEY_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mål.
        /// </summary>
        public static string CONTRACT_TARGET {
            get {
                return ResourceManager.GetString("CONTRACT_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to til.
        /// </summary>
        public static string CONTRACT_TO {
            get {
                return ResourceManager.GetString("CONTRACT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trening.
        /// </summary>
        public static string CONTRACT_TRAINING {
            get {
                return ResourceManager.GetString("CONTRACT_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treningsøvelser.
        /// </summary>
        public static string CONTRACT_TRAINING_EXERCISES {
            get {
                return ResourceManager.GetString("CONTRACT_TRAINING_EXERCISES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svake KPI`er.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svake KPIer : Treningsøvelser frem mot neste mål.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_EXERCISE_EXERCISES_TOWARDS_THE_NEXT_GOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svake KPIer Mål.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_GOALS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_GOALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svake KPIer : Repeterende treningsdetaljer.
        /// </summary>
        public static string CONTRACT_WEAK_KPIS_REPETITIVE_TRAINING_DETAILS {
            get {
                return ResourceManager.GetString("CONTRACT_WEAK_KPIS_REPETITIVE_TRAINING_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva.
        /// </summary>
        public static string CONTRACT_WHAT {
            get {
                return ResourceManager.GetString("CONTRACT_WHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvorfor.
        /// </summary>
        public static string CONTRACT_WHY {
            get {
                return ResourceManager.GetString("CONTRACT_WHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du svarte.
        /// </summary>
        public static string CONTRACT_YOU_ANSWERED {
            get {
                return ResourceManager.GetString("CONTRACT_YOU_ANSWERED", resourceCulture);
            }
        }
    }
}
