CREATE TABLE [dbo].[IpsSurveyPlan] (
    [IpsSurveyPlanID]             INT            IDENTITY (1, 1) NOT NULL,
    [Name]                        VARCHAR (50)   NULL,
    [Description]                 VARCHAR (1000) NULL,
    [MonthlyPrice]                NUMERIC (8, 2) NULL,
    [AnualPrice]                  NUMERIC (8, 2) NULL,
    [NoOfQuestions]               INT            NULL,
    [Whitelabel]                  INT            NULL,
    [NoOfResponse]                INT            NULL,
    [MultipleTypesquestions]      INT            NULL,
    [PreDefinedTemplates]         INT            NULL,
    [UnicodeSupport]              INT            NULL,
    [Pagelogic]                   INT            NULL,
    [Questionlogic]               INT            NULL,
    [Randomassignment]            INT            NULL,
    [QuestionAnswerPiping]        INT            NULL,
    [QuestionRandomization]       INT            NULL,
    [ThemeCustomization]          INT            NULL,
    [RandomizeSortAnswerChoices]  INT            NULL,
    [PresetVisualThemes]          INT            NULL,
    [SurveyCompletionProgressBar] INT            NULL,
    [AutoNumbering]               INT            NULL,
    [PrintablePDF]                INT            NULL,
    [ClosedOnDateOrQuota]         INT            NULL,
    [508Compliant]                INT            NULL,
    [RichMedia]                   INT            NULL,
    [CustomRedirect]              INT            NULL,
    [SpellCheck]                  INT            NULL,
    [CustomThankYou]              INT            NULL,
    [ImportQuestionAnswer]        INT            NULL,
    [BranchingLogic]              INT            NULL,
    [DragDropFeature]             INT            NULL,
    [SurveyBank]                  INT            NULL,
    [CustomizeStyles]             INT            NULL,
    [CustomizeLookFeel]           INT            NULL,
    [RealTimeResults]             INT            NULL,
    [TextAnalysis]                INT            NULL,
    [MultipleCustomReports]       INT            NULL,
    [FilteringResponse]           INT            NULL,
    [Charts]                      INT            NULL,
    [SharingResponses]            INT            NULL,
    [DailyemailSupport]           INT            NULL,
    [ExpertSupport]               INT            NULL,
    [ExpeditedEmail]              INT            NULL,
    [PowerfulCharts]              INT            NULL,
    [ExportResults]               INT            NULL,
    [LocationReportsForPolls]     INT            NULL,
    [ResponseFiltering]           INT            NULL,
    [TrackResponseTime]           INT            NULL,
    [CreatedDate]                 DATETIME       CONSTRAINT [DF_IpsSurveyPlan_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                   INT            NULL,
    [IsDeleted]                   BIT            CONSTRAINT [DF_IpsSurveyPlan_IsDeleted] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_IpsSurveyPlan] PRIMARY KEY CLUSTERED ([IpsSurveyPlanID] ASC)
);

