CREATE TABLE [dbo].[Organizations_tmp] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [Name]              NVARCHAR (250)  NULL,
    [ParentId]          INT             NULL,
    [organisationFlag]  BIT             NULL,
    [CustomerCode]      NVARCHAR (50)   NULL,
    [AddressLine1]      NVARCHAR (250)  NULL,
    [AddressLine2]      NVARCHAR (250)  NULL,
    [AddressLine3]      NVARCHAR (250)  NULL,
    [ZipPostalCode]     NVARCHAR (50)   NULL,
    [City]              NVARCHAR (150)  NULL,
    [Country]           NVARCHAR (150)  NULL,
    [Phone]             NVARCHAR (50)   NULL,
    [Fax]               NVARCHAR (50)   NULL,
    [Email]             NVARCHAR (150)  NULL,
    [Website]           NVARCHAR (150)  NULL,
    [LogoLink]          NVARCHAR (150)  NULL,
    [OrgCode]           NVARCHAR (50)   NULL,
    [PostAddressLine1]  NVARCHAR (250)  NULL,
    [PostAddressLine2]  NVARCHAR (250)  NULL,
    [PostAddressLine3]  NVARCHAR (250)  NULL,
    [PostZipPostalCode] NVARCHAR (50)   NULL,
    [PostCity]          NVARCHAR (150)  NULL,
    [PostCountry]       NVARCHAR (150)  NULL,
    [Logo]              VARBINARY (MAX) NULL,
    [IsDepartment]      BIT             NULL,
    CONSTRAINT [PK_Organizations_tmp] PRIMARY KEY CLUSTERED ([Id] ASC)
);

