CREATE TABLE [dbo].[Organizations] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [Name]                 NVARCHAR (250) NOT NULL,
    [ParentId]             INT            NULL,
    [IndustryId]           INT            NULL,
    [ZipPostalCode]        NVARCHAR (50)  NULL,
    [City]                 NVARCHAR (150) NULL,
    [Phone]                NVARCHAR (50)  NULL,
    [Fax]                  NVARCHAR (50)  NULL,
    [Email]                NVARCHAR (150) NULL,
    [Website]              NVARCHAR (150) NULL,
    [LogoLink]             NVARCHAR (150) NULL,
    [OrgCode]              NVARCHAR (50)  NULL,
    [PostAddressLine1]     NVARCHAR (250) NULL,
    [PostAddressLine2]     NVARCHAR (250) NULL,
    [PostAddressLine3]     NVARCHAR (250) NULL,
    [PostZipPostalCode]    NVARCHAR (50)  NULL,
    [PostCity]             NVARCHAR (150) NULL,
    [PostCountry]          NVARCHAR (150) NULL,
    [CountryId]            INT            NULL,
    [Address]              NVARCHAR (MAX) NULL,
    [ContactName]          NVARCHAR (50)  NULL,
    [State]                NVARCHAR (50)  NULL,
    [VisitingAddress]      NVARCHAR (500) NULL,
    [VisitingZip]          NVARCHAR (50)  NULL,
    [VisitingCity]         NVARCHAR (150) NULL,
    [VisitingCountryId]    INT            NULL,
    [Skype]                NVARCHAR (150) NULL,
    [ContactEmail]         NVARCHAR (150) NULL,
    [ContactPhone]         NVARCHAR (50)  NULL,
    [Twitter]              NVARCHAR (150) NULL,
    [Facebook]             NVARCHAR (500) NULL,
    [LinkedIn]             NVARCHAR (500) NULL,
    [Pinterest]            NVARCHAR (500) NULL,
    [IPSGroup]             NVARCHAR (500) NULL,
    [VisitingState]        NVARCHAR (50)  NULL,
    [ContactTitleId]       INT            NULL,
    [ContactRoleId]        INT            NULL,
    [ParentOrganizationId] INT            NULL,
    [OrganizationTypeId]   INT            NULL,
    [CreatedOn]            DATETIME       NULL,
    [CreatedBy]            INT            NULL,
    [UpdatedOn]            DATETIME       NULL,
    [UpdatedBy]            INT            NULL,
    [CSVFile]              NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Organizations] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Organizations_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([Id]),
    CONSTRAINT [FK_Organizations_Industries1] FOREIGN KEY ([IndustryId]) REFERENCES [dbo].[Industries] ([Id]),
    CONSTRAINT [FK_Organizations_LookupItemsContactRole] FOREIGN KEY ([ContactRoleId]) REFERENCES [dbo].[LookupItems] ([Id]),
    CONSTRAINT [FK_Organizations_LookupItemsContactTitle] FOREIGN KEY ([ContactTitleId]) REFERENCES [dbo].[LookupItems] ([Id]),
    CONSTRAINT [FK_Organizations_Organizations] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Organizations] ([Id]),
    CONSTRAINT [FK_Organizations_VisitingCountries] FOREIGN KEY ([VisitingCountryId]) REFERENCES [dbo].[Countries] ([Id])
);





