CREATE TABLE [dbo].[Stages] (
    [Id]                                               INT           IDENTITY (1, 1) NOT NULL,
    [Name]                                             NVARCHAR (50) NOT NULL,
    [StageGroupId]                                     INT           NOT NULL,
    [StartDateTime]                                    DATETIME      NOT NULL,
    [EndDateTime]                                      DATETIME      NOT NULL,
    [EvaluationDurationMinutes]                        INT           NULL,
    [EmailNotification]                                BIT           NOT NULL,
    [SMSNotification]                                  BIT           NOT NULL,
    [GreenAlarmParticipantTemplateId]                  INT           NULL,
    [GreenAlarmTime]                                   DATETIME      NULL,
    [YellowAlarmParticipantTemplateId]                 INT           NULL,
    [YellowAlarmTime]                                  DATETIME      NULL,
    [RedAlarmParticipantTemplateId]                    INT           NULL,
    [RedAlarmTime]                                     DATETIME      NULL,
    [ExternalStartNotificationTemplateId]              INT           NULL,
    [ExternalCompletedNotificationTemplateId]          INT           NULL,
    [ExternalResultsNotificationTemplateId]            INT           NULL,
    [EvaluatorStartNotificationTemplateId]             INT           NULL,
    [EvaluatorCompletedNotificationTemplateId]         INT           NULL,
    [EvaluatorResultsNotificationTemplateId]           INT           NULL,
    [TrainerStartNotificationTemplateId]               INT           NULL,
    [TrainerCompletedNotificationTemplateId]           INT           NULL,
    [TrainerResultsNotificationTemplateId]             INT           NULL,
    [ManagerStartNotificationTemplateId]               INT           NULL,
    [ManagerCompletedNotificationTemplateId]           INT           NULL,
    [ManagerResultsNotificationTemplateId]             INT           NULL,
    [ManagerId]                                        INT           NULL,
    [TrainerId]                                        INT           NULL,
    [InvitedAt]                                        DATETIME      NULL,
    [GreenAlarmEvaluatorTemplateId]                    INT           NULL,
    [GreenAlarmManagerTemplateId]                      INT           NULL,
    [GreenAlarmTrainerTemplateId]                      INT           NULL,
    [YellowAlarmEvaluatorTemplateId]                   INT           NULL,
    [YellowAlarmManagerTemplateId]                     INT           NULL,
    [YellowAlarmTrainerTemplateId]                     INT           NULL,
    [RedAlarmEvaluatorTemplateId]                      INT           NULL,
    [RedAlarmManagerTemplateId]                        INT           NULL,
    [RedAlarmTrainerTemplateId]                        INT           NULL,
    [ProjectManagerStartNotificationTemplateId]        INT           NULL,
    [ProjectManagerCompletedNotificationTemplateId]    INT           NULL,
    [ProjectManagerResultsNotificationTemplateId]      INT           NULL,
    [ProjectManagerId]                                 INT           NULL,
    [GreenAlarmProjectManagerTemplateId]               INT           NULL,
    [YellowAlarmProjectManagerTemplateId]              INT           NULL,
    [RedAlarmProjectManagerTemplateId]                 INT           NULL,
    [FinalScoreManagerStartNotificationTemplateId]     INT           NULL,
    [FinalScoreManagerCompletedNotificationTemplateId] INT           NULL,
    [FinalScoreManagerResultsNotificationTemplateId]   INT           NULL,
    [GreenAlarmFinalScoreManagerTemplateId]            INT           NULL,
    [YellowAlarmFinalScoreManagerTemplateId]           INT           NULL,
    [RedAlarmFinalScoreManagerTemplateId]              INT           NULL,
    [EvaluationStartDate]                              DATETIME      NULL,
    [EvaluationEndDate]                                DATETIME      NULL,
    [CreatedOn]                                        DATETIME      NULL,
    [CreatedBy]                                        INT           NULL,
    [ModifiedOn]                                       DATETIME      NULL,
    [ModifiedBy]                                       INT           NULL,
    [IsPaused]                                         BIT           CONSTRAINT [DF_Stages_IsPaused] DEFAULT ((0)) NOT NULL,
    [PausedAt]                                         DATETIME      NULL,
    [IsStopped]                                        BIT           CONSTRAINT [DF_Stages_IsStopped] DEFAULT ((0)) NOT NULL,
    [StoppedAt]                                        DATETIME      NULL,
    CONSTRAINT [PK_Stages] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Stages_EvaluatorCompletedNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([EvaluatorCompletedNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_EvaluatorResultsNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([EvaluatorResultsNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_EvaluatorStartNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([EvaluatorStartNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ExternalCompletedNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ExternalCompletedNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ExternalResultsNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ExternalResultsNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ExternalStartNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ExternalStartNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_GreenAlarmEvaluatorTemplateId_NotificationTemplates] FOREIGN KEY ([GreenAlarmEvaluatorTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_GreenAlarmManagerTemplateId_NotificationTemplates] FOREIGN KEY ([GreenAlarmManagerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_GreenAlarmParticipantTemplateId_NotificationTemplates] FOREIGN KEY ([GreenAlarmParticipantTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_GreenAlarmTrainerTemplateId_NotificationTemplates] FOREIGN KEY ([GreenAlarmTrainerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ManagerCompletedNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ManagerCompletedNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ManagerId_Users] FOREIGN KEY ([ManagerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Stages_ManagerResultsNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ManagerResultsNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_ManagerStartNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([ManagerStartNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_RedAlarmEvaluatorTemplateId_NotificationTemplates] FOREIGN KEY ([RedAlarmEvaluatorTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_RedAlarmManagerTemplateId_NotificationTemplates] FOREIGN KEY ([RedAlarmManagerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_RedAlarmParticipantTemplateId_NotificationTemplates] FOREIGN KEY ([RedAlarmParticipantTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_RedAlarmTrainerTemplateId_NotificationTemplates] FOREIGN KEY ([RedAlarmTrainerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_StageGroups] FOREIGN KEY ([StageGroupId]) REFERENCES [dbo].[StageGroups] ([Id]),
    CONSTRAINT [FK_Stages_TrainerCompletedNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([TrainerCompletedNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_TrainerId_Users] FOREIGN KEY ([TrainerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Stages_TrainerResultsNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([TrainerResultsNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_TrainerStartNotificationTemplateId_NotificationTemplates] FOREIGN KEY ([TrainerStartNotificationTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_YellowAlarmEvaluatorTemplateId_NotificationTemplates] FOREIGN KEY ([YellowAlarmEvaluatorTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_YellowAlarmManagerTemplateId_NotificationTemplates] FOREIGN KEY ([YellowAlarmManagerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_YellowAlarmParticipantTemplateId_NotificationTemplates] FOREIGN KEY ([YellowAlarmParticipantTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id]),
    CONSTRAINT [FK_Stages_YellowAlarmTrainerTemplateId_NotificationTemplates] FOREIGN KEY ([YellowAlarmTrainerTemplateId]) REFERENCES [dbo].[NotificationTemplates] ([Id])
);













