CREATE TABLE [dbo].[Users_tmp] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]      NVARCHAR (250) NULL,
    [SurName]        NVARCHAR (250) NULL,
    [UnitLeader]     BIT            NULL,
    [OrganizationId] INT            NULL,
    [Culture]        NVARCHAR (50)  NULL,
    [Email]          NVARCHAR (150) NULL,
    [DirectPhone]    NVARCHAR (50)  NULL,
    [MobilePhone]    NVARCHAR (50)  NULL,
    [Position]       NVARCHAR (50)  NULL,
    [Password]       NVARCHAR (50)  NULL,
    [PasswordHash]   NVARCHAR (150) NULL,
    [Comments]       NVARCHAR (500) NULL,
    [IsLocked]       BIT            NULL,
    [UserType]       CHAR (1)       NULL,
    [ViewChildren]   BIT            NULL,
    [ViewSiblings]   BIT            NULL,
    [fax]            NVARCHAR (50)  NULL,
    [skype]          NVARCHAR (50)  NULL,
    [twitter]        NVARCHAR (MAX) NULL,
    [facebook]       NVARCHAR (MAX) NULL,
    [linkedin]       NVARCHAR (MAX) NULL,
    [webSite]        NVARCHAR (100) NULL,
    [userName]       NVARCHAR (50)  NULL,
    [Address1]       NVARCHAR (100) NULL,
    [Address2]       NVARCHAR (100) NULL,
    [City]           NVARCHAR (50)  NULL,
    [Country]        NVARCHAR (50)  NULL,
    [PostalCode]     NCHAR (10)     NULL,
    [IsSuperAdmin]   BIT            CONSTRAINT [DF_Users_IsSuperAdmin] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Users_tmp] PRIMARY KEY CLUSTERED ([Id] ASC)
);

