CREATE TABLE [dbo].[Users] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [UserKey]        NVARCHAR (128) NULL,
    [UserTypeId]     INT            NOT NULL,
    [OrganizationId] INT            NULL,
    [FirstName]      NVARCHAR (250) NULL,
    [LastName]       NVARCHAR (250) NULL,
    [BirthDate]      DATE           NULL,
    [Gender]         CHAR (1)       NULL,
    [Country]        NVARCHAR (50)  NULL,
    [City]           NVARCHAR (50)  NULL,
    [State]          NVARCHAR (50)  NULL,
    [Address1]       NVARCHAR (350) NULL,
    [Address2]       NVARCHAR (350) NULL,
    [Zip]            NCHAR (6)      NULL,
    [ImagePath]      NVARCHAR (MAX) NULL,
    [Skype]          NVARCHAR (50)  NULL,
    [Twitter]        NVARCHAR (MAX) NULL,
    [Facebook]       NVARCHAR (MAX) NULL,
    [Linkedin]       NVARCHAR (MAX) NULL,
    [MobileNo]       NVARCHAR (MAX) NULL,
    [WorkPhoneNo]    NVARCHAR (MAX) NULL,
    [PrivatePhoneNo] NVARCHAR (MAX) NULL,
    [WorkEmail]      NVARCHAR (255) NULL,
    [PrivateEmail]   NVARCHAR (255) NULL,
    [CultureId]      INT            NULL,
    [WebSite]        NVARCHAR (250) NULL,
    [Remarks]        NVARCHAR (MAX) NULL,
    [IsActive]       BIT            CONSTRAINT [DF_Users_IsActive] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Users_Cultures] FOREIGN KEY ([CultureId]) REFERENCES [dbo].[Cultures] ([Id]),
    CONSTRAINT [FK_Users_Organizations] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organizations] ([Id]),
    CONSTRAINT [FK_Users_UserTypes] FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserTypes] ([Id])
);

