//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public int QuestionId { get; set; }
        public bool IsCorrect { get; set; }
        public Nullable<int> StageId { get; set; }
        public string Answer1 { get; set; }
        public Nullable<int> KPIType { get; set; }
        public string Comment { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual KPIType KPIType1 { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
