//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmsPage
    {
        public int PageID { get; set; }
        public string Title { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyWord { get; set; }
        public string MetaDescription { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public string PageContent { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> PageAccessCode { get; set; }
    
        public virtual LookupItem LookupItem { get; set; }
    }
}
