//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Organizations = new HashSet<Organization>();
            this.Organizations1 = new HashSet<Organization>();
        }
    
        public int Id { get; set; }
        public string CountryName { get; set; }
        public string FlagImage { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Organization> Organizations1 { get; set; }
    }
}
