//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public Culture()
        {
            this.Users = new HashSet<User>();
            this.NotificationTemplates = new HashSet<NotificationTemplate>();
        }
    
        public int Id { get; set; }
        public string CultureName { get; set; }
        public string CultureIdentifier { get; set; }
        public string Region { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<NotificationTemplate> NotificationTemplates { get; set; }
    }
}
