//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerSalesDatas = new HashSet<CustomerSalesData>();
            this.ProspectingCustomers = new HashSet<ProspectingCustomer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> AssignedUserId { get; set; }
        public string CSVFile { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CustomerSalesData> CustomerSalesDatas { get; set; }
        public virtual ICollection<ProspectingCustomer> ProspectingCustomers { get; set; }
    }
}
