//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesData
    {
        public CustomerSalesData()
        {
            this.ProspectingCustomers = new HashSet<ProspectingCustomer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string RegistrationNo { get; set; }
        public string Seller { get; set; }
        public Nullable<int> Offer { get; set; }
        public string CSVFile { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ProspectingCustomer> ProspectingCustomers { get; set; }
    }
}
