//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.QuestionMaterials = new HashSet<QuestionMaterial>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public string ResourceType { get; set; }
    
        public virtual ICollection<QuestionMaterial> QuestionMaterials { get; set; }
    }
}
