//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationParticipant
    {
        public EvaluationParticipant()
        {
            this.Answers = new HashSet<Answer>();
            this.EvaluationParticipants1 = new HashSet<EvaluationParticipant>();
            this.EvaluationAgreements = new HashSet<EvaluationAgreement>();
            this.StagesEvolutions = new HashSet<StagesEvolution>();
            this.SurveyResults = new HashSet<SurveyResult>();
            this.EvaluationStatuses = new HashSet<EvaluationStatus>();
            this.MilestoneAgreementGoals = new HashSet<MilestoneAgreementGoal>();
            this.ProspectingGoalInfoes = new HashSet<ProspectingGoalInfo>();
        }
    
        public int StageGroupId { get; set; }
        public int UserId { get; set; }
        public bool IsLocked { get; set; }
        public int EvaluationRoleId { get; set; }
        public int Id { get; set; }
        public Nullable<int> EvaluateeId { get; set; }
        public Nullable<bool> IsSelfEvaluation { get; set; }
        public Nullable<System.DateTime> Invited { get; set; }
        public bool IsScoreManager { get; set; }
        public Nullable<System.DateTime> ResultSendOutAt { get; set; }
        public bool IsResultSendOut { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<EvaluationParticipant> EvaluationParticipants1 { get; set; }
        public virtual EvaluationParticipant EvaluationParticipant1 { get; set; }
        public virtual EvaluationRole EvaluationRole { get; set; }
        public virtual ICollection<EvaluationAgreement> EvaluationAgreements { get; set; }
        public virtual ICollection<StagesEvolution> StagesEvolutions { get; set; }
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
        public virtual ICollection<EvaluationStatus> EvaluationStatuses { get; set; }
        public virtual ICollection<MilestoneAgreementGoal> MilestoneAgreementGoals { get; set; }
        public virtual StageGroup StageGroup { get; set; }
        public virtual ICollection<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
    }
}
