//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationAgreement
    {
        public EvaluationAgreement()
        {
            this.Trainings = new HashSet<Training>();
            this.MilestoneAgreementGoals = new HashSet<MilestoneAgreementGoal>();
        }
    
        public int StageId { get; set; }
        public int ParticipantId { get; set; }
        public int QuestionId { get; set; }
        public int KPIType { get; set; }
        public Nullable<decimal> ShortGoal { get; set; }
        public string Comment { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> FinalScore { get; set; }
        public Nullable<decimal> MidGoal { get; set; }
        public Nullable<decimal> LongGoal { get; set; }
        public Nullable<decimal> FinalGoal { get; set; }
        public Nullable<bool> IsFinalScoreCopied { get; set; }
    
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
        public virtual KPIType KPIType1 { get; set; }
        public virtual ICollection<MilestoneAgreementGoal> MilestoneAgreementGoals { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
