//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationStatus
    {
        public Nullable<int> StageId { get; set; }
        public int ParticipantId { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public int DurationMinutes { get; set; }
        public Nullable<System.DateTime> InvitedAt { get; set; }
        public Nullable<System.DateTime> RemindAt { get; set; }
        public bool IsOpen { get; set; }
        public Nullable<int> StageEvolutionId { get; set; }
        public int Id { get; set; }
    
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual StagesEvolution StagesEvolution { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
