//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpsAttachment
    {
        public IpsAttachment()
        {
            this.IpsAttachmentFileDetails = new HashSet<IpsAttachmentFileDetail>();
            this.IpsAttachmentUsers = new HashSet<IpsAttachmentUser>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<IpsAttachmentFileDetail> IpsAttachmentFileDetails { get; set; }
        public virtual ICollection<IpsAttachmentUser> IpsAttachmentUsers { get; set; }
    }
}
