//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPSData : DbContext
    {
        public IPSData()
            : base("name=IPSData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AnswerType> AnswerTypes { get; set; }
        public virtual DbSet<Culture> Cultures { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DurationMetric> DurationMetrics { get; set; }
        public virtual DbSet<EvaluationRole> EvaluationRoles { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<KTMedalRule> KTMedalRules { get; set; }
        public virtual DbSet<Link_TeamUsers> Link_TeamUsers { get; set; }
        public virtual DbSet<Link_TrainingParticipants> Link_TrainingParticipants { get; set; }
        public virtual DbSet<MeasureUnit> MeasureUnits { get; set; }
        public virtual DbSet<ProfileCategory> ProfileCategories { get; set; }
        public virtual DbSet<ProfileScaleSettingsRule> ProfileScaleSettingsRules { get; set; }
        public virtual DbSet<ProfileType> ProfileTypes { get; set; }
        public virtual DbSet<ScorecardGoal> ScorecardGoals { get; set; }
        public virtual DbSet<ScorecardPerspective> ScorecardPerspectives { get; set; }
        public virtual DbSet<StructureLevel> StructureLevels { get; set; }
        public virtual DbSet<TaskCategoryList> TaskCategoryLists { get; set; }
        public virtual DbSet<TaskPriorityListItem> TaskPriorityListItems { get; set; }
        public virtual DbSet<TaskPriorityList> TaskPriorityLists { get; set; }
        public virtual DbSet<TaskStatusListItem> TaskStatusListItems { get; set; }
        public virtual DbSet<TaskStatusList> TaskStatusLists { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<JobPosition> JobPositions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<ScaleCategory> ScaleCategories { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Scale> Scales { get; set; }
        public virtual DbSet<TrainingLevel> TrainingLevels { get; set; }
        public virtual DbSet<TrainingType> TrainingTypes { get; set; }
        public virtual DbSet<TrainingDescription> TrainingDescriptions { get; set; }
        public virtual DbSet<LookupItem> LookupItems { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<PerformanceGroup> PerformanceGroups { get; set; }
        public virtual DbSet<TrainingMaterial> TrainingMaterials { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<TaskList> TaskLists { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Link_PerformanceGroupSkills> Link_PerformanceGroupSkills { get; set; }
        public virtual DbSet<EvaluationParticipant> EvaluationParticipants { get; set; }
        public virtual DbSet<EvaluationAgreement> EvaluationAgreements { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<TaskCategoryListItem> TaskCategoryListItems { get; set; }
        public virtual DbSet<NotificationTemplate> NotificationTemplates { get; set; }
        public virtual DbSet<KPIType> KPITypes { get; set; }
        public virtual DbSet<Link_ProjectUsers> Link_ProjectUsers { get; set; }
        public virtual DbSet<ReminderType> ReminderTypes { get; set; }
        public virtual DbSet<Trend> Trends { get; set; }
        public virtual DbSet<ExerciseMetric> ExerciseMetrics { get; set; }
        public virtual DbSet<Link_Training_NotificationType_NotificationInterval> Link_Training_NotificationType_NotificationInterval { get; set; }
        public virtual DbSet<NotificationInterval> NotificationIntervals { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<CmsPage> CmsPages { get; set; }
        public virtual DbSet<IpsPlanRole> IpsPlanRoles { get; set; }
        public virtual DbSet<IpsPlan> IpsPlans { get; set; }
        public virtual DbSet<IPSPlanField> IPSPlanFields { get; set; }
        public virtual DbSet<IPSPlanFieldsLookup> IPSPlanFieldsLookups { get; set; }
        public virtual DbSet<IPSPlanFeature> IPSPlanFeatures { get; set; }
        public virtual DbSet<ScaleRange> ScaleRanges { get; set; }
        public virtual DbSet<HelpCategory> HelpCategories { get; set; }
        public virtual DbSet<HelpContent> HelpContents { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<PlanFeaturesKey> PlanFeaturesKeys { get; set; }
        public virtual DbSet<PortfolioCategory> PortfolioCategories { get; set; }
        public virtual DbSet<PortfolioImage> PortfolioImages { get; set; }
        public virtual DbSet<TemplateCategory> TemplateCategories { get; set; }
        public virtual DbSet<TemplateContent> TemplateContents { get; set; }
        public virtual DbSet<TemplateContentImage> TemplateContentImages { get; set; }
        public virtual DbSet<PortfolioProject> PortfolioProjects { get; set; }
        public virtual DbSet<PossibleAnswer> PossibleAnswers { get; set; }
        public virtual DbSet<StagesEvolution> StagesEvolutions { get; set; }
        public virtual DbSet<StagesEvolutionQuestion> StagesEvolutionQuestions { get; set; }
        public virtual DbSet<SurveyResult> SurveyResults { get; set; }
        public virtual DbSet<EvaluationStatus> EvaluationStatuses { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<QuestionMaterial> QuestionMaterials { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual DbSet<TaskScaleRanx> TaskScaleRanges { get; set; }
        public virtual DbSet<TaskScale> TaskScales { get; set; }
        public virtual DbSet<TrainingMaterialRating> TrainingMaterialRatings { get; set; }
        public virtual DbSet<TaskActivity> TaskActivities { get; set; }
        public virtual DbSet<ProjectRole> ProjectRoles { get; set; }
        public virtual DbSet<ProjectGoal> ProjectGoals { get; set; }
        public virtual DbSet<ProjectSteeringGroup> ProjectSteeringGroups { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Link_ProfileTags> Link_ProfileTags { get; set; }
        public virtual DbSet<ProjectGlobalSetting> ProjectGlobalSettings { get; set; }
        public virtual DbSet<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<IpsEmail> IpsEmails { get; set; }
        public virtual DbSet<NotificationTemplateType> NotificationTemplateTypes { get; set; }
        public virtual DbSet<TrainingNote> TrainingNotes { get; set; }
        public virtual DbSet<MilestoneAgreementGoal> MilestoneAgreementGoals { get; set; }
        public virtual DbSet<ProjectDefaultNotificationSetting> ProjectDefaultNotificationSettings { get; set; }
        public virtual DbSet<StageGroup> StageGroups { get; set; }
        public virtual DbSet<ProspectingActivity> ProspectingActivities { get; set; }
        public virtual DbSet<ProspectingGoalActivityInfo> ProspectingGoalActivityInfoes { get; set; }
        public virtual DbSet<ProspectingSkillGoal> ProspectingSkillGoals { get; set; }
        public virtual DbSet<ProspectingCustomerResult> ProspectingCustomerResults { get; set; }
        public virtual DbSet<ProspectingSchedule> ProspectingSchedules { get; set; }
        public virtual DbSet<ProspectingActivityLog> ProspectingActivityLogs { get; set; }
        public virtual DbSet<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
        public virtual DbSet<ProspectingGoalScaleRanx> ProspectingGoalScaleRanges { get; set; }
        public virtual DbSet<ProspectingGoalScale> ProspectingGoalScales { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerSalesData> CustomerSalesDatas { get; set; }
        public virtual DbSet<TrainingFeedback> TrainingFeedbacks { get; set; }
        public virtual DbSet<ProspectingActivityFeedback> ProspectingActivityFeedbacks { get; set; }
        public virtual DbSet<ProspectingCustomer> ProspectingCustomers { get; set; }
        public virtual DbSet<ExpiredProspectingActivityReason> ExpiredProspectingActivityReasons { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<ProspectingCustomerOfferDetail> ProspectingCustomerOfferDetails { get; set; }
        public virtual DbSet<OfferClosingDetail> OfferClosingDetails { get; set; }
        public virtual DbSet<ProspectingCustomerSalesAgreedData> ProspectingCustomerSalesAgreedDatas { get; set; }
        public virtual DbSet<IPSEMailAttachment> IPSEMailAttachments { get; set; }
        public virtual DbSet<IpsAttachmentFileDetail> IpsAttachmentFileDetails { get; set; }
        public virtual DbSet<IpsAttachment> IpsAttachments { get; set; }
        public virtual DbSet<IpsAttachmentUser> IpsAttachmentUsers { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<DailyEvaluation> DailyEvaluations { get; set; }
        public virtual DbSet<SensorData> SensorDatas { get; set; }
    }
}
