//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpsEmail
    {
        public IpsEmail()
        {
            this.IPSEMailAttachments = new HashSet<IPSEMailAttachment>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public System.DateTime SentTime { get; set; }
        public string FromAddress { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string BCCAddress { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
    
        public virtual ICollection<IPSEMailAttachment> IPSEMailAttachments { get; set; }
    }
}
