//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSPlanFieldsLookup
    {
        public int PlanFieldMappingID { get; set; }
        public Nullable<int> IpsPlanLabelID { get; set; }
        public string LabelText { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual IPSPlanField IPSPlanField { get; set; }
        public virtual LookupItem LookupItem { get; set; }
    }
}
