//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPSPlanField
    {
        public IPSPlanField()
        {
            this.IPSPlanFieldsLookups = new HashSet<IPSPlanFieldsLookup>();
            this.IPSPlanFeatures = new HashSet<IPSPlanFeature>();
        }
    
        public int IpsPlanLabelID { get; set; }
        public Nullable<int> PlanTypeID { get; set; }
        public string PlanLabelID { get; set; }
    
        public virtual ICollection<IPSPlanFieldsLookup> IPSPlanFieldsLookups { get; set; }
        public virtual ICollection<IPSPlanFeature> IPSPlanFeatures { get; set; }
    }
}
