//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosition
    {
        public JobPosition()
        {
            this.Users = new HashSet<User>();
            this.Skills = new HashSet<Skill>();
            this.PerformanceGroups = new HashSet<PerformanceGroup>();
            this.Profiles = new HashSet<Profile>();
        }
    
        public int Id { get; set; }
        public string JobPosition1 { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<PerformanceGroup> PerformanceGroups { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
    }
}
