//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIType
    {
        public KPIType()
        {
            this.Answers = new HashSet<Answer>();
            this.EvaluationAgreements = new HashSet<EvaluationAgreement>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<EvaluationAgreement> EvaluationAgreements { get; set; }
    }
}
