//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link_Training_NotificationType_NotificationInterval
    {
        public int TrainingId { get; set; }
        public int NotificationTypeId { get; set; }
        public int NotificationIntervalId { get; set; }
    
        public virtual NotificationInterval NotificationInterval { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual Training Training { get; set; }
    }
}
