//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link_PerformanceGroupSkills
    {
        public Link_PerformanceGroupSkills()
        {
            this.Questions = new HashSet<Question>();
            this.Trainings = new HashSet<Training>();
        }
    
        public int Id { get; set; }
        public int PerformanceGroupId { get; set; }
        public int SkillId { get; set; }
        public Nullable<int> SubSkillId { get; set; }
        public Nullable<decimal> Benchmark { get; set; }
        public string Weight { get; set; }
        public string CSF { get; set; }
        public string Action { get; set; }
    
        public virtual PerformanceGroup PerformanceGroup { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual Skill Skill1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
