//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupItem
    {
        public LookupItem()
        {
            this.Organizations = new HashSet<Organization>();
            this.Organizations1 = new HashSet<Organization>();
            this.CmsPages = new HashSet<CmsPage>();
            this.IpsPlanRoles = new HashSet<IpsPlanRole>();
            this.IpsPlans = new HashSet<IpsPlan>();
            this.IPSPlanFieldsLookups = new HashSet<IPSPlanFieldsLookup>();
            this.PlanFeaturesKeys = new HashSet<PlanFeaturesKey>();
            this.PlanFeaturesKeys1 = new HashSet<PlanFeaturesKey>();
        }
    
        public int Id { get; set; }
        public string LookupItemType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Organization> Organizations1 { get; set; }
        public virtual ICollection<CmsPage> CmsPages { get; set; }
        public virtual ICollection<IpsPlanRole> IpsPlanRoles { get; set; }
        public virtual ICollection<IpsPlan> IpsPlans { get; set; }
        public virtual ICollection<IPSPlanFieldsLookup> IPSPlanFieldsLookups { get; set; }
        public virtual ICollection<PlanFeaturesKey> PlanFeaturesKeys { get; set; }
        public virtual ICollection<PlanFeaturesKey> PlanFeaturesKeys1 { get; set; }
    }
}
