//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public NotificationTemplate()
        {
            this.UserRecurrentNotificationSettings = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings1 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings2 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings3 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings4 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings5 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings6 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings7 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings8 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings9 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings10 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings11 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings12 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings13 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings14 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings15 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings16 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings17 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings18 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings19 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings20 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings21 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings22 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings23 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings24 = new HashSet<UserRecurrentNotificationSetting>();
            this.UserRecurrentNotificationSettings25 = new HashSet<UserRecurrentNotificationSetting>();
            this.Tasks = new HashSet<Task>();
            this.Stages = new HashSet<Stage>();
            this.Stages1 = new HashSet<Stage>();
            this.Stages2 = new HashSet<Stage>();
            this.Stages3 = new HashSet<Stage>();
            this.Stages4 = new HashSet<Stage>();
            this.Stages5 = new HashSet<Stage>();
            this.Stages6 = new HashSet<Stage>();
            this.Stages7 = new HashSet<Stage>();
            this.Stages8 = new HashSet<Stage>();
            this.Stages9 = new HashSet<Stage>();
            this.Stages10 = new HashSet<Stage>();
            this.Stages11 = new HashSet<Stage>();
            this.Stages12 = new HashSet<Stage>();
            this.Stages13 = new HashSet<Stage>();
            this.Stages14 = new HashSet<Stage>();
            this.Stages15 = new HashSet<Stage>();
            this.Stages16 = new HashSet<Stage>();
            this.Stages17 = new HashSet<Stage>();
            this.Stages18 = new HashSet<Stage>();
            this.Stages19 = new HashSet<Stage>();
            this.Stages20 = new HashSet<Stage>();
            this.Stages21 = new HashSet<Stage>();
            this.Stages22 = new HashSet<Stage>();
            this.Stages23 = new HashSet<Stage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CultureId { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string SMSMessage { get; set; }
        public Nullable<int> EvaluationRoleId { get; set; }
        public string UIMessage { get; set; }
        public Nullable<int> StageTypeId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> NotificationTemplateTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedAsRoleId { get; set; }
        public string ModifiedAsRoleId { get; set; }
        public bool IsDefualt { get; set; }
        public Nullable<int> StateTypeId { get; set; }
        public Nullable<int> ProjectTypeId { get; set; }
        public Nullable<int> ProfileTypeId { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual EvaluationRole EvaluationRole { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings1 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings2 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings3 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings4 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings5 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings6 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings7 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings8 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings9 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings10 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings11 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings12 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings13 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings14 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings15 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings16 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings17 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings18 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings19 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings20 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings21 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings22 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings23 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings24 { get; set; }
        public virtual ICollection<UserRecurrentNotificationSetting> UserRecurrentNotificationSettings25 { get; set; }
        public virtual NotificationTemplateType NotificationTemplateType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Stage> Stages1 { get; set; }
        public virtual ICollection<Stage> Stages2 { get; set; }
        public virtual ICollection<Stage> Stages3 { get; set; }
        public virtual ICollection<Stage> Stages4 { get; set; }
        public virtual ICollection<Stage> Stages5 { get; set; }
        public virtual ICollection<Stage> Stages6 { get; set; }
        public virtual ICollection<Stage> Stages7 { get; set; }
        public virtual ICollection<Stage> Stages8 { get; set; }
        public virtual ICollection<Stage> Stages9 { get; set; }
        public virtual ICollection<Stage> Stages10 { get; set; }
        public virtual ICollection<Stage> Stages11 { get; set; }
        public virtual ICollection<Stage> Stages12 { get; set; }
        public virtual ICollection<Stage> Stages13 { get; set; }
        public virtual ICollection<Stage> Stages14 { get; set; }
        public virtual ICollection<Stage> Stages15 { get; set; }
        public virtual ICollection<Stage> Stages16 { get; set; }
        public virtual ICollection<Stage> Stages17 { get; set; }
        public virtual ICollection<Stage> Stages18 { get; set; }
        public virtual ICollection<Stage> Stages19 { get; set; }
        public virtual ICollection<Stage> Stages20 { get; set; }
        public virtual ICollection<Stage> Stages21 { get; set; }
        public virtual ICollection<Stage> Stages22 { get; set; }
        public virtual ICollection<Stage> Stages23 { get; set; }
    }
}
