//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferClosingDetail
    {
        public int Id { get; set; }
        public int ProspectingCustomerOfferDetailId { get; set; }
        public int Status { get; set; }
        public string Reason { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime ClosedTime { get; set; }
        public int ClosedBy { get; set; }
        public Nullable<int> Possibility { get; set; }
        public string WhatNext { get; set; }
    
        public virtual ProspectingCustomerOfferDetail ProspectingCustomerOfferDetail { get; set; }
    }
}
