//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioImage
    {
        public int ProtfolioProjectImageID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> DisplayOnTop { get; set; }
        public Nullable<int> PortfolioProjectID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PortfolioProject PortfolioProject { get; set; }
    }
}
