//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioCategory
    {
        public PortfolioCategory()
        {
            this.PortfolioProjects = new HashSet<PortfolioProject>();
        }
    
        public int PortfolioCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<PortfolioProject> PortfolioProjects { get; set; }
    }
}
