//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.PerformanceGroups = new HashSet<PerformanceGroup>();
            this.JobPositions = new HashSet<JobPosition>();
            this.Link_ProfileTags = new HashSet<Link_ProfileTags>();
            this.StageGroups = new HashSet<StageGroup>();
            this.ProspectingGoalInfoes = new HashSet<ProspectingGoalInfo>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public int ProfileTypeId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> MedalRuleId { get; set; }
        public Nullable<int> ScaleId { get; set; }
        public Nullable<int> ScaleSettingsRuleId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public bool IsActive { get; set; }
        public int KPIWeak { get; set; }
        public int KPIStrong { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> QuestionDisplayRuleId { get; set; }
        public bool SetKPIInSurvey { get; set; }
        public Nullable<bool> RandomizeQuestions { get; set; }
        public Nullable<bool> AllowRevisitAnsweredQuestions { get; set; }
        public Nullable<int> PassScore { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedAsRoleId { get; set; }
        public string ModifiedAsRoleId { get; set; }
    
        public virtual Industry Industry { get; set; }
        public virtual KTMedalRule KTMedalRule { get; set; }
        public virtual ICollection<PerformanceGroup> PerformanceGroups { get; set; }
        public virtual ProfileCategory ProfileCategory { get; set; }
        public virtual ProfileScaleSettingsRule ProfileScaleSettingsRule { get; set; }
        public virtual ProfileType ProfileType { get; set; }
        public virtual Scale Scale { get; set; }
        public virtual StructureLevel StructureLevel { get; set; }
        public virtual ICollection<JobPosition> JobPositions { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Link_ProfileTags> Link_ProfileTags { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<StageGroup> StageGroups { get; set; }
        public virtual ICollection<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
