//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Link_ProjectUsers = new HashSet<Link_ProjectUsers>();
            this.Profiles = new HashSet<Profile>();
            this.ProjectGlobalSettings = new HashSet<ProjectGlobalSetting>();
            this.ProjectGoals = new HashSet<ProjectGoal>();
            this.ProjectSteeringGroups = new HashSet<ProjectSteeringGroup>();
            this.ProjectDefaultNotificationSettings = new HashSet<ProjectDefaultNotificationSetting>();
            this.ProspectingGoalInfoes = new HashSet<ProspectingGoalInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string VisionStatement { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ExpectedStartDate { get; set; }
        public System.DateTime ExpectedEndDate { get; set; }
        public string MissionStatement { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public string CreatedAsRoleId { get; set; }
        public string ModifiedAsRoleId { get; set; }
    
        public virtual ICollection<Link_ProjectUsers> Link_ProjectUsers { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<ProjectGlobalSetting> ProjectGlobalSettings { get; set; }
        public virtual ICollection<ProjectGoal> ProjectGoals { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProjectSteeringGroup> ProjectSteeringGroups { get; set; }
        public virtual ICollection<ProjectDefaultNotificationSetting> ProjectDefaultNotificationSettings { get; set; }
        public virtual ICollection<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
    }
}
