//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRole
    {
        public ProjectRole()
        {
            this.Link_ProjectUsers = new HashSet<Link_ProjectUsers>();
            this.ProjectSteeringGroups = new HashSet<ProjectSteeringGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Link_ProjectUsers> Link_ProjectUsers { get; set; }
        public virtual ICollection<ProjectSteeringGroup> ProjectSteeringGroups { get; set; }
    }
}
