//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSteeringGroup
    {
        public ProjectSteeringGroup()
        {
            this.Link_ProjectUsers = new HashSet<Link_ProjectUsers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<Link_ProjectUsers> Link_ProjectUsers { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual Project Project { get; set; }
    }
}
