//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingCustomer
    {
        public ProspectingCustomer()
        {
            this.ProspectingCustomerResults = new HashSet<ProspectingCustomerResult>();
            this.ProspectingSchedules = new HashSet<ProspectingSchedule>();
            this.ProspectingCustomerOfferDetails = new HashSet<ProspectingCustomerOfferDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Detail { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ProspectingGoalId { get; set; }
        public Nullable<int> CustomerSaleDataId { get; set; }
        public int AssignedToUserId { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public int AssignedBy { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerSalesData CustomerSalesData { get; set; }
        public virtual ICollection<ProspectingCustomerResult> ProspectingCustomerResults { get; set; }
        public virtual ProspectingGoalInfo ProspectingGoalInfo { get; set; }
        public virtual ICollection<ProspectingSchedule> ProspectingSchedules { get; set; }
        public virtual ICollection<ProspectingCustomerOfferDetail> ProspectingCustomerOfferDetails { get; set; }
    }
}
