//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingGoalScale
    {
        public ProspectingGoalScale()
        {
            this.ProspectingGoalInfoes = new HashSet<ProspectingGoalInfo>();
            this.ProspectingGoalScaleRanges = new HashSet<ProspectingGoalScaleRanx>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ScaleCategoryId { get; set; }
        public int MeasureUnitId { get; set; }
        public bool IncludeNotRelevant { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual ICollection<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
        public virtual ICollection<ProspectingGoalScaleRanx> ProspectingGoalScaleRanges { get; set; }
        public virtual ScaleCategory ScaleCategory { get; set; }
    }
}
