//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingCustomerResult
    {
        public ProspectingCustomerResult()
        {
            this.ProspectingSchedules = new HashSet<ProspectingSchedule>();
            this.ProspectingCustomerSalesAgreedDatas = new HashSet<ProspectingCustomerSalesAgreedData>();
        }
    
        public int Id { get; set; }
        public int ProspectingCustomerId { get; set; }
        public int ProspectingActivityId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public bool IsDone { get; set; }
        public string Description { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool IsNoMeeting { get; set; }
        public bool IsMeeting { get; set; }
        public bool IsFollowUp { get; set; }
        public Nullable<int> CustomerInterestRate { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsServiceAgreed { get; set; }
        public decimal ServiceAmount { get; set; }
        public int ProspectingType { get; set; }
        public bool IsSales { get; set; }
        public string SalesNotification { get; set; }
    
        public virtual ProspectingActivity ProspectingActivity { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ICollection<ProspectingSchedule> ProspectingSchedules { get; set; }
        public virtual ProspectingCustomer ProspectingCustomer { get; set; }
        public virtual ICollection<ProspectingCustomerSalesAgreedData> ProspectingCustomerSalesAgreedDatas { get; set; }
    }
}
