//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingSchedule
    {
        public int Id { get; set; }
        public Nullable<int> ProspectingCustomerId { get; set; }
        public Nullable<int> ProspectingActivityId { get; set; }
        public Nullable<int> ProspectingCustomerResultId { get; set; }
        public bool IsMeeting { get; set; }
        public bool IsFollowUp { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string Agenda { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModiffiedBy { get; set; }
        public Nullable<int> TaskId { get; set; }
        public bool IsServiceAgreed { get; set; }
        public int ProspectingType { get; set; }
        public string Notification { get; set; }
    
        public virtual ProspectingActivity ProspectingActivity { get; set; }
        public virtual ProspectingCustomerResult ProspectingCustomerResult { get; set; }
        public virtual ProspectingCustomer ProspectingCustomer { get; set; }
    }
}
