//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingCustomerOfferDetail
    {
        public ProspectingCustomerOfferDetail()
        {
            this.OfferClosingDetails = new HashSet<OfferClosingDetail>();
        }
    
        public int Id { get; set; }
        public int ProspectingCustomerId { get; set; }
        public string Description { get; set; }
        public decimal OfferPrice { get; set; }
        public System.DateTime OfferSentTime { get; set; }
        public int OfferSentBy { get; set; }
        public System.DateTime OfferFollowUpScheduleDate { get; set; }
    
        public virtual ProspectingCustomer ProspectingCustomer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OfferClosingDetail> OfferClosingDetails { get; set; }
    }
}
