//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingActivity
    {
        public ProspectingActivity()
        {
            this.ProspectingCustomerResults = new HashSet<ProspectingCustomerResult>();
            this.ProspectingSchedules = new HashSet<ProspectingSchedule>();
            this.ProspectingActivityLogs = new HashSet<ProspectingActivityLog>();
            this.ProspectingActivityFeedbacks = new HashSet<ProspectingActivityFeedback>();
            this.ExpiredProspectingActivityReasons = new HashSet<ExpiredProspectingActivityReason>();
        }
    
        public int Id { get; set; }
        public int ProspectingGoalActivityId { get; set; }
        public string Name { get; set; }
        public System.DateTime ActivityStart { get; set; }
        public System.DateTime ActivityEnd { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
    
        public virtual ProspectingGoalActivityInfo ProspectingGoalActivityInfo { get; set; }
        public virtual ICollection<ProspectingCustomerResult> ProspectingCustomerResults { get; set; }
        public virtual ICollection<ProspectingSchedule> ProspectingSchedules { get; set; }
        public virtual ICollection<ProspectingActivityLog> ProspectingActivityLogs { get; set; }
        public virtual ICollection<ProspectingActivityFeedback> ProspectingActivityFeedbacks { get; set; }
        public virtual ICollection<ExpiredProspectingActivityReason> ExpiredProspectingActivityReasons { get; set; }
    }
}
