//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingCustomerSalesAgreedData
    {
        public int Id { get; set; }
        public int SalesCategoryId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int ProspectingCustomerId { get; set; }
        public int ProspectingActivityId { get; set; }
        public int ProspectingCustomerResultId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ProspectingCustomerResult ProspectingCustomerResult { get; set; }
    }
}
