//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingSkillGoal
    {
        public int Id { get; set; }
        public int ProspectingGoalId { get; set; }
        public int SkillId { get; set; }
        public int Goal { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual ProspectingGoalInfo ProspectingGoalInfo { get; set; }
    }
}
