//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingGoalInfo
    {
        public ProspectingGoalInfo()
        {
            this.ProspectingGoalActivityInfoes = new HashSet<ProspectingGoalActivityInfo>();
            this.ProspectingSkillGoals = new HashSet<ProspectingSkillGoal>();
            this.ProspectingCustomers = new HashSet<ProspectingCustomer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
        public Nullable<System.DateTime> GoalStartDate { get; set; }
        public Nullable<System.DateTime> GoalEndDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ProspectingGoalScaleId { get; set; }
        public int ProspectingType { get; set; }
    
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<ProspectingGoalActivityInfo> ProspectingGoalActivityInfoes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProspectingSkillGoal> ProspectingSkillGoals { get; set; }
        public virtual ProspectingGoalScale ProspectingGoalScale { get; set; }
        public virtual ICollection<ProspectingCustomer> ProspectingCustomers { get; set; }
        public virtual Task Task { get; set; }
    }
}
