//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingActivityFeedback
    {
        public int Id { get; set; }
        public Nullable<int> ProspectingActivityId { get; set; }
        public Nullable<int> Rating { get; set; }
        public string WorkedWell { get; set; }
        public string WorkedNotWell { get; set; }
        public string WhatNextDescription { get; set; }
        public Nullable<int> TimeSpentMinutes { get; set; }
        public Nullable<System.DateTime> FeedbackDateTime { get; set; }
        public Nullable<System.DateTime> ActvityStartTime { get; set; }
        public Nullable<System.DateTime> ActvityEndTime { get; set; }
        public Nullable<bool> IsRecurrences { get; set; }
        public string RecurrencesRule { get; set; }
        public Nullable<bool> IsParticipantPaused { get; set; }
        public Nullable<System.DateTime> ParticipantPausedAt { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
    
        public virtual ProspectingActivity ProspectingActivity { get; set; }
    }
}
