//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectingGoalActivityInfo
    {
        public ProspectingGoalActivityInfo()
        {
            this.ProspectingActivities = new HashSet<ProspectingActivity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public int ProspectingGoalId { get; set; }
        public int ActivityTime { get; set; }
        public int BreakTime { get; set; }
        public int TotalActivities { get; set; }
        public System.DateTime ActivityStartTime { get; set; }
        public System.DateTime ActivityEndTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int ActivityCalculationType { get; set; }
        public string Frequency { get; set; }
    
        public virtual ICollection<ProspectingActivity> ProspectingActivities { get; set; }
        public virtual ProspectingGoalInfo ProspectingGoalInfo { get; set; }
    }
}
