//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScaleRange
    {
        public int Id { get; set; }
        public int ScaleId { get; set; }
        public decimal Min { get; set; }
        public decimal Max { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
    
        public virtual Scale Scale { get; set; }
    }
}
