//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scale
    {
        public Scale()
        {
            this.Questions = new HashSet<Question>();
            this.PerformanceGroups = new HashSet<PerformanceGroup>();
            this.Profiles = new HashSet<Profile>();
            this.ScaleRanges = new HashSet<ScaleRange>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ScaleCategoryId { get; set; }
        public int MeasureUnitId { get; set; }
        public bool IncludeNotRelevant { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> ProfileType { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual ProfileType ProfileType1 { get; set; }
        public virtual ScaleCategory ScaleCategory { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<PerformanceGroup> PerformanceGroups { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<ScaleRange> ScaleRanges { get; set; }
    }
}
