//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int Id { get; set; }
        public int TrainingId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Yaw { get; set; }
        public int Pitch { get; set; }
        public int Roll { get; set; }
    }
}
