//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.Skills1 = new HashSet<Skill>();
            this.Industries = new HashSet<Industry>();
            this.JobPositions = new HashSet<JobPosition>();
            this.Questions = new HashSet<Question>();
            this.Trainings = new HashSet<Training>();
            this.Link_PerformanceGroupSkills = new HashSet<Link_PerformanceGroupSkills>();
            this.Link_PerformanceGroupSkills1 = new HashSet<Link_PerformanceGroupSkills>();
            this.TrainingDescriptions = new HashSet<TrainingDescription>();
            this.ProspectingSkillGoals = new HashSet<ProspectingSkillGoal>();
            this.ProspectingCustomerResults = new HashSet<ProspectingCustomerResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> StructureLevelId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ProfileTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedAsRoleId { get; set; }
        public string ModifiedAsRoleId { get; set; }
        public Nullable<int> SeqNo { get; set; }
    
        public virtual ProfileType ProfileType { get; set; }
        public virtual ICollection<Skill> Skills1 { get; set; }
        public virtual Skill Skill1 { get; set; }
        public virtual StructureLevel StructureLevel { get; set; }
        public virtual ICollection<Industry> Industries { get; set; }
        public virtual ICollection<JobPosition> JobPositions { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
        public virtual ICollection<Link_PerformanceGroupSkills> Link_PerformanceGroupSkills { get; set; }
        public virtual ICollection<Link_PerformanceGroupSkills> Link_PerformanceGroupSkills1 { get; set; }
        public virtual ICollection<TrainingDescription> TrainingDescriptions { get; set; }
        public virtual ICollection<ProspectingSkillGoal> ProspectingSkillGoals { get; set; }
        public virtual ICollection<ProspectingCustomerResult> ProspectingCustomerResults { get; set; }
    }
}
