//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagesEvolution
    {
        public StagesEvolution()
        {
            this.StagesEvolution1 = new HashSet<StagesEvolution>();
            this.StagesEvolutionQuestions = new HashSet<StagesEvolutionQuestion>();
            this.SurveyResults = new HashSet<SurveyResult>();
            this.EvaluationStatuses = new HashSet<EvaluationStatus>();
        }
    
        public int Id { get; set; }
        public int OriginalStageId { get; set; }
        public Nullable<int> ParentStageEvolutionId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int ParticipantId { get; set; }
    
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual ICollection<StagesEvolution> StagesEvolution1 { get; set; }
        public virtual StagesEvolution StagesEvolution2 { get; set; }
        public virtual ICollection<StagesEvolutionQuestion> StagesEvolutionQuestions { get; set; }
        public virtual ICollection<SurveyResult> SurveyResults { get; set; }
        public virtual ICollection<EvaluationStatus> EvaluationStatuses { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
