//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResult
    {
        public SurveyResult()
        {
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
        }
    
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public Nullable<int> StageId { get; set; }
        public int TimeSpent { get; set; }
        public Nullable<int> StageEvolutionId { get; set; }
    
        public virtual EvaluationParticipant EvaluationParticipant { get; set; }
        public virtual StagesEvolution StagesEvolution { get; set; }
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
