//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.ProspectingGoalInfoes = new HashSet<ProspectingGoalInfo>();
            this.TaskActivities = new HashSet<TaskActivity>();
            this.Tasks1 = new HashSet<Task>();
            this.TrainingFeedbacks = new HashSet<TrainingFeedback>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int TaskListId { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ParentTaskID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> TimeEstimateMinutes { get; set; }
        public Nullable<int> TimeSpentMinutes { get; set; }
        public Nullable<int> AssignedToId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<int> NotificationTemplateId { get; set; }
        public bool IsSMSNotification { get; set; }
        public bool IsEmailNotification { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> EmailBefore { get; set; }
        public Nullable<int> SmsBefore { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> MeetingNotificationTemplateId { get; set; }
        public Nullable<int> FollowUpNotificationTemplateId { get; set; }
        public Nullable<int> SalesNotificationTemplateId { get; set; }
    
        public virtual NotificationTemplate NotificationTemplate { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<ProspectingGoalInfo> ProspectingGoalInfoes { get; set; }
        public virtual ICollection<TaskActivity> TaskActivities { get; set; }
        public virtual TaskCategoryListItem TaskCategoryListItem { get; set; }
        public virtual TaskList TaskList { get; set; }
        public virtual TaskPriorityListItem TaskPriorityListItem { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual Task Task1 { get; set; }
        public virtual TaskStatusListItem TaskStatusListItem { get; set; }
        public virtual Training Training { get; set; }
        public virtual ICollection<TrainingFeedback> TrainingFeedbacks { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
