//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskActivity
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public Nullable<System.DateTime> RecurrenceStartTime { get; set; }
        public Nullable<System.DateTime> RecurrenceEndTime { get; set; }
        public string RecurrencesRule { get; set; }
        public Nullable<System.DateTime> ActivityDateTime { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
