//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskScale
    {
        public TaskScale()
        {
            this.TaskScaleRanges = new HashSet<TaskScaleRanx>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ScaleStart { get; set; }
        public int ScaleEnd { get; set; }
        public int ScaleInterval { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<TaskScaleRanx> TaskScaleRanges { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
