//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateContentImage
    {
        public int TemplateImageID { get; set; }
        public Nullable<int> TemplateContentID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsPrimaryImage { get; set; }
    
        public virtual TemplateContent TemplateContent { get; set; }
    }
}
