//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCategory
    {
        public TemplateCategory()
        {
            this.TemplateContents = new HashSet<TemplateContent>();
            this.TemplateCategory1 = new HashSet<TemplateCategory>();
        }
    
        public int TemplateCategoryID { get; set; }
        public Nullable<int> TemplateTypeID { get; set; }
        public string Title { get; set; }
        public string Meta { get; set; }
        public string Icon { get; set; }
        public string KeyWord { get; set; }
        public string Description { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<bool> IsParentCategory { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<TemplateContent> TemplateContents { get; set; }
        public virtual ICollection<TemplateCategory> TemplateCategory1 { get; set; }
        public virtual TemplateCategory TemplateCategory2 { get; set; }
    }
}
