//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int TestimonialID { get; set; }
        public string ClientName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Logo { get; set; }
    }
}
