//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public Training()
        {
            this.Link_TrainingParticipants = new HashSet<Link_TrainingParticipants>();
            this.TrainingMaterials = new HashSet<TrainingMaterial>();
            this.Skills = new HashSet<Skill>();
            this.Link_PerformanceGroupSkills = new HashSet<Link_PerformanceGroupSkills>();
            this.EvaluationAgreements = new HashSet<EvaluationAgreement>();
            this.Link_Training_NotificationType_NotificationInterval = new HashSet<Link_Training_NotificationType_NotificationInterval>();
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
            this.TrainingNotes = new HashSet<TrainingNote>();
            this.TrainingFeedbacks = new HashSet<TrainingFeedback>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string What { get; set; }
        public string How { get; set; }
        public string Why { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> LevelId { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DurationMetricId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> HowMany { get; set; }
        public Nullable<int> ExerciseMetricId { get; set; }
        public Nullable<int> HowManySets { get; set; }
        public Nullable<int> HowManyActions { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsNotificationBySMS { get; set; }
        public bool IsNotificationByEmail { get; set; }
        public Nullable<int> NotificationTemplateId { get; set; }
        public Nullable<int> EmailBefore { get; set; }
        public Nullable<int> SmsBefore { get; set; }
        public Nullable<int> EvaluatorFeedbackRecurrence { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedAsRoleId { get; set; }
        public string ModifiedAsRoleId { get; set; }
        public string DescriptiveFrequency { get; set; }
    
        public virtual DurationMetric DurationMetric { get; set; }
        public virtual ICollection<Link_TrainingParticipants> Link_TrainingParticipants { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual TrainingLevel TrainingLevel { get; set; }
        public virtual ICollection<TrainingMaterial> TrainingMaterials { get; set; }
        public virtual TrainingType TrainingType { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<Link_PerformanceGroupSkills> Link_PerformanceGroupSkills { get; set; }
        public virtual ICollection<EvaluationAgreement> EvaluationAgreements { get; set; }
        public virtual ExerciseMetric ExerciseMetric { get; set; }
        public virtual ICollection<Link_Training_NotificationType_NotificationInterval> Link_Training_NotificationType_NotificationInterval { get; set; }
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TrainingNote> TrainingNotes { get; set; }
        public virtual ICollection<TrainingFeedback> TrainingFeedbacks { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
