//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMaterialRating
    {
        public int Id { get; set; }
        public Nullable<int> TrainingMaterialId { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> RatingBy { get; set; }
        public Nullable<System.DateTime> RatingSubmitDate { get; set; }
    
        public virtual TrainingMaterial TrainingMaterial { get; set; }
        public virtual User User { get; set; }
    }
}
